[tool.poetry]
name = "telegram_channel_files_manager"
version = "0.1.0"
description = ""
authors = ["Kurbanov Bulat <kurbanovbul@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.95.1"
httpx = "^0.24.0"
alembic = "^1.10.4"
uvicorn = {extras = ["standard"], version = "^0.22.0"}
arq = "^0.25.0"
prometheus-fastapi-instrumentator = "^6.0.0"
uvloop = "^0.17.0"
orjson = "^3.8.12"
sentry-sdk = "^1.22.2"
ormar = {extras = ["postgresql"], version = "^0.12.1"}
pydantic = "^1.10.4"
redis = {extras = ["hiredis"], version = "^4.5.5"}
msgpack = "^1.0.5"

[tool.poetry.group.dev.dependencies]
pre-commit = "^2.21.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.vscode
  | \venv
  | alembic
)/
'''

[tool.ruff]
fix = true
target-version = "py311"
src = ["app"]
line-length=88
ignore = []
select = ["B", "C", "E", "F", "W", "B9", "I001"]
exclude = [
    # No need to traverse our git directory
    ".git",
    # There's no value in checking cache directories
    "__pycache__",
    # The conf file is mostly autogenerated, ignore it
    "src/app/alembic",
]

[tool.ruff.flake8-bugbear]
extend-immutable-calls = ["fastapi.File", "fastapi.Form", "fastapi.Security"]

[tool.ruff.mccabe]
max-complexity = 15

[tool.ruff.isort]
known-first-party = ["core", "app"]
force-sort-within-sections = true
force-wrap-aliases = true
section-order = ["future", "standard-library", "base_framework", "framework_ext", "third-party", "first-party", "local-folder"]
lines-after-imports = 2

[tool.ruff.isort.sections]
base_framework = ["fastapi",]
framework_ext = ["starlette"]

[tool.ruff.pyupgrade]
keep-runtime-typing = true
